// Generated by CoffeeScript 1.6.3
(function() {
  var fs, server, spawn, temp, ws, _;

  ws = require('ws');

  _ = require('underscore');

  spawn = require('child_process').spawn;

  fs = require('fs');

  temp = require('temp');

  server = new ws.Server({
    port: 8080
  });

  console.log("Server running.");

  server.on('connection', function(ws) {
    var maze_data;
    console.log("Connection received.");
    ws.send("CONNECTED");
    maze_data = [];
    return temp.mkdir(function(err, dirPath) {
      ws.send(function() {
        return "READY";
      });
      return ws.on('message', function(message) {
        if (/^\[MAZE\].*/.test(message)) {
          return fs.writeFiile("" + dirPath + "/maze.json", message, function(err) {
            var logic;
            if (err) {
              return console.log(err);
            } else {
              ws.send("MAZE LOADED");
              logic = spawn('python', ['../backend/MazeLogic.py', "" + dirPath + "/maze.json", "../backend/RandomRobotController.py"]);
              return logic.stdout.on('data', function(data) {
                return maze_data.push(data);
              });
            }
          });
        } else if (message === "STEP") {
          if (maze_data) {
            return ws.send("NO_DATA");
          } else {
            ws.send(maze_data[0]);
            return maze_data = maze_data.slice(1);
          }
        }
      });
    });
  });

}).call(this);
